import time
import os

def clear():
    os.system("clear")

def sleep(num):
    time.sleep(num)

def loading_animation():
    print("Loading")
    sleep(0.2)
    clear()
    print("Loading.")
    sleep(0.2)
    clear()
    print("Loading..")
    sleep(0.2)
    clear()
    print("Loading...")
    sleep(0.2)
    clear()
    print("Loading")
    sleep(0.2)
    clear()
    print("Loading.")
    sleep(0.2)
    clear()
    print("Loading..")
    sleep(0.2)
    clear()
    print("Loading...")
    sleep(0.2)
    clear()
    print("Loading")
    sleep(0.2)
    clear()
    print("Loading.")
    sleep(0.2)
    clear()
    print("Loading..")
    sleep(0.2)
    clear()
    print("Loading...")
    sleep(0.2)
    clear()
    print("Loading")
    sleep(0.2)
    clear()
    print("Loading.")
    sleep(0.2)
    clear()
    print("Loading..")
    sleep(0.2)
    clear()
    print("Loading...")
    sleep(0.2)
    clear()


